local Dict = Rkr.Dict
local List = Rkr.List

local t = { a = 10, b = 20, c = 30 }

---@type dict<string, integer>
local d

describe("Dict", function()
    before_each(function() d = Dict(t) end)

    describe("construct", function()
        it("creates empty dict", function()
            expect(Dict()).deep_equals(Dict.new())
                .and_it.deep_equals(Dict.fromkeys())
                .and_it.deep_equals(Dict.fromkeys({}))
                .and_it.deep_equals(Dict({}))
                .and_it.deep_equals(Dict.new({}))
        end)
        it("creates dict from table", function()
            local empty = Dict({ a = nil, b = nil, c = nil })
            expect(d).deep_equals(Dict.new(t))
            expect(Dict.fromkeys(t)).deep_equals(empty)
        end)
        it("creates dict from an iterator", function()
            local empty = Dict({ a = nil, b = nil, c = nil })
            expect(Dict.fromkeys(d:keys())).deep_equals(empty)
        end)
        it("throws KeyError for unhasbale key types", function()
            expect(function() Dict.new({ [List({ 1, 2 })] = "a" }) end).errors("TypeError")
        end)
        it("throws lua error for nil key", function()
            expect(function() Dict.new({ [nil] = "a" }) end).errors()
        end)
    end)

    describe("index access", function()
        it("returns value for existing key", function()
            expect(d["a"]).equals(10)
        end)
        it("throws KeyError for missing key", function()
            expect_index(d, "z").errors("KeyError")
        end)
        it("throws TypeError for nil key", function()
            expect_index(d, nil).errors("TypeError")
        end)
    end)

    describe("assign", function()
        before_each(function() d = Dict(t) end)

        it("assigns value to existing key", function()
            expect_assign(d, "a", 99)
                .deep_equals(Dict({ a = 99, b = 20, c = 30 }))
        end)
        it("adds new key when assigning", function()
            expect_assign(d, "z", 5)
                .deep_equals(Dict({ a = 10, b = 20, c = 30, z = 5 }))
        end)
        it("throws error for invalid key type", function()
            expect_assign(d, List({ 1, 2 }), 5).errors("TypeError")
        end)
        it("throws TypeError for nil key", function()
            expect_assign(d, nil, 5).errors("TypeError")
        end)
    end)

    describe("length", function()
        it("returns correct size using # operator", function()
            expect(d).has_length(3)
            expect(#d).equals(3)
        end)
        it("returns correct size using len()", function()
            expect(d:len()).equals(3)
        end)
        it("empty dict has length 0", function()
            expect(Dict()).has_length(0)
        end)
    end)

    describe("contains", function()
        it("returns true when key exists", function()
            expect(d).contains("a")
            expect(d:contains("a")).equals(true)
        end)
        it("returns false when key does not exist", function()
            expect(d).to_not.contains("z")
            expect(d:contains("z")).equals(false)
        end)
        it("returns false on empty dict", function()
            expect(Dict()).to_not.contains("z")
            expect(Dict():contains("z")).equals(false)
        end)
    end)

    describe("get", function()
        it("returns value when key exists", function()
            expect(d:get("a")).equals(10)
        end)
        it("returns nil when key missing and no default provided", function()
            expect(d:get("z")).equals(nil)
        end)
        it("returns default when key missing", function()
            expect(d:get("z", 99)).equals(99)
        end)
    end)

    describe("pop", function()
        before_each(function() d = Dict(t) end)

        it("removes and returns value for key", function()
            expect(d:pop("a")).equals(10)
            expect(d).has_length(3)
                .and_it.contains("b")
                .and_it.contains("c")
        end)
        it("returns default when key missing", function()
            expect(d:pop("z", 77)).equals(77)
            expect(d).deep_equals(Dict(t))
        end)

        it("throws KeyError when key missing and no default", function()
            expect(function() d:pop("z") end).errors("KeyError")
        end)
    end)

    describe("popitem", function()
        it("removes and returns the last key-value pair added", function()
            for _ = 1, 5 do
                d["test"] = 5
                local k, v = d:popitem()
                expect(#d).equals(3)
                expect(k).equals("test")
                expect(v).equals(5)
            end
        end)

        it("throws KeyError when empty", function()
            local empty = Dict()
            expect(function() empty:popitem() end).errors("KeyError")
        end)
    end)

    describe("clear", function()
        it("removes all entries", function()
            d:clear()
            expect(d).deep_equals(Dict())
        end)
    end)

    describe("update", function()
        it("updates from table", function()
            d:update({ a = 99, z = 5 })
            expect(d).deep_equals(Dict({ a = 99, b = 20, c = 30, z = 5 }))
        end)

        it("updates from another dict", function()
            local other = Dict({ x = 1 })
            d:update(other)
            expect(d).deep_equals(Dict({ a = 10, b = 20, c = 30, x = 1 }))
        end)
    end)

    describe("copy", function()
        it("returns independent copy", function()
            local new = d:copy()
            expect(new).deep_equals(Dict(t))
            expect(rawequal(new, d)).equals(false)
        end)

        it("mutations do not affect original", function()
            local new = d:copy()
            new["z"] = 999
            expect(d).to_not.contains("z")
            expect(new).contains("z")
        end)
    end)

    describe("keys, values, items", function()
        it("keys returns all keys", function()
            local keys = List.list(d:keys())
            expect(keys).has_length(3)
                .and_it.contains("a")
                .and_it.contains("b")
                .and_it.contains("c")
        end)

        it("values returns all values", function()
            local values = List.list(d:values())
            expect(values).has_length(3)
                .and_it.contains(10)
                .and_it.contains(20)
                .and_it.contains(30)
        end)

        it("items returns key-value pairs", function()
            expect(List.list(d:items())).has_length(3) --TODO fix this...
                .and_it.contains("a")
                .and_it.contains("b")
                .and_it.contains("c")
        end)

        it("callable dict returns keys iterator", function()
            expect(List.list(d())).has_length(3)
                .and_it.contains("a")
                .and_it.contains("b")
                .and_it.contains("c")
        end)
    end)

    describe("iteration", function()
        it("iterates over keys by default", function()
            local keys = {}
            for k in d:keys() do table.insert(keys, k) end
            expect(#keys).equals(3)
        end)
    end)

    describe("equality", function()
        it("dicts with same pairs are equal", function()
            expect(Dict({ a = 10, b = 20, c = 30 })).deep_equals(d)
        end)

        it("dicts with different pairs are not equal", function()
            expect(Dict({ a = 1 })).to_not.deep_equals(d)
        end)
    end)

    describe("tostring", function()
        it("returns formatted string representation", function()
            local str = tostring(d)
            expect(type(str)).equals("string")
        end)

        it("returns {} for empty dict", function()
            expect(tostring(Dict())).equals("{}")
        end)
    end)

    describe("heterogeneous values", function()
        it("supports mixed value types", function()
            local mixed = Dict({
                a = 1,
                b = "x",
                c = true,
                d = { 1, 2 }
            })
            expect(#mixed).equals(4)
        end)
    end)
end)
